CREATE TABLE CUSTOMER (
  ID IDENTITY NOT NULL PRIMARY KEY,
  NAME VARCHAR NOT NULL,
  EMAIL VARCHAR NOT NULL,
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  VERSION BIGINT
);
