server.servlet.context-path: / # Context path of the application.
server.compression.enabled: true
server.compression.mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/stream+json,application/x-ndjson
server.compression.min-response-size: 1024
server.http2.enabled: true
server.port: ${SERVER_PORT:8080}

spring.application.name: '@project.artifactId@'
spring.application.version: '@project.version@'
spring.profiles.active: ${SPRING_PROFILES_ACTIVE:local}
spring.main.allow-bean-definition-overriding: true # Enable bean override

# ----------------------------------------
# ACTUATOR PROPERTIES
# ----------------------------------------
# ENDPOINTS WEB CONFIGURATION
management.endpoints.web.exposure.include: '*' # Endpoint IDs that should be included or '*' for all.
management.endpoints.web.exposure.exclude:  # Endpoint IDs that should be excluded or '*' for all.
management.endpoints.web.base-path: /management # Base path for Web endpoints. Relative to server.servlet.context-path or management.server.servlet.context-path if management.server.port is configured.
management.endpoints.web.path-mapping.health: healthcheck
# HEALTH ENDPOINT
management.endpoint.health.cache.time-to-live: 0ms # Maximum time that a response can be cached.
management.endpoint.health.enabled: true # Whether to enable the health endpoint.
management.endpoint.health.roles:  # Roles used to determine whether or not a user is authorized to be shown details. When empty, all authenticated users are authorized.
management.endpoint.health.show-details: always # When to show full health details.
management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: true
# INFO CONTRIBUTORS (InfoContributorProperties)
management.info.build.enabled: true # Whether to enable build info.
management.info.defaults.enabled: true # Whether to enable default info contributors.
management.info.env.enabled: true # Whether to enable environment info.
management.info.git.enabled: true # Whether to enable git info.
management.info.git.mode: full # Mode to use to expose git information.
# METRICS
management.endpoint.metrics.enabled: true
management.endpoint.prometheus.enabled: true

---
spring.config.activate.on-profile: local

# OPENAPI :: SPRINGDOC :: SWAGGER
springdoc:
  api-docs:
    groups.enabled: true
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger
    display-request-duration: true
    groups-order: DESC
    operations-sorter: alpha
    tags-sorter: alpha


# Micrometer Datadog configuration.
management.datadog.metrics.export.enabled: true
management.datadog.metrics.export.api-key: "DD-API-KEY"
management.datadog.metrics.export.uri: https://api.datadoghq.eu
management.datadog.metrics.export.step: 30s
#-- Micrometer Datadog configuration for local agent.
management.statsd.metrics.export.enabled: false
management.statsd.metrics.export.host: localhost
management.statsd.metrics.export.port: 8125
management.statsd.metrics.export.protocol: udp
management.statsd.metrics.export.flavor: datadog
#--
management.metrics.tags:
  application: ${spring.application.name}
  env: ${spring.profiles.active}
  environment: ${spring.profiles.active}
