spring.datasource.h2.url: jdbc:h2:mem:testdb;MODE=PostgreSQL
spring.datasource.h2.driverClassName: org.h2.Driver
spring.datasource.h2.username: sa
spring.h2.console.enabled: true

# JPA specific configs
spring.jpa.open-in-view: false
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL95Dialect
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
spring.jpa.properties.hibernate.show_sql: false
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.properties.hibernate.use_sql: true
spring.jpa.properties.hibernate.hibernate.dialect: true
spring.jpa.properties.hibernate.id.new_generator_mappings: false
spring.jpa.properties.hibernate.search.autoregister_listeners: false
spring.jpa.properties.hibernate.bytecode.use_reflection_optimizer: false

spring.flyway.enabled: true
spring.flyway.locations: classpath:/db/migration
